CREATE TABLE kt
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name               VARCHAR(255),
    code               VARCHAR(255),
    created_by         VARCHAR(255),
    created_date       TIMESTAMP WITHOUT TIME ZONE,
    deleted            BOOLEAN                                 NOT NULL,
    deleted_by         VARCHAR(255),
    deleted_date       TIMESTAMP WITHOUT TIME ZONE,

    last_modified_by   VARCHAR(255),
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,

    CONSTRAINT pk_kt PRIMARY KEY (id)
);


INSERT INTO public.kt (id, code, name, created_by, created_date, deleted, deleted_by, deleted_date, last_modified_by, last_modified_date) VALUES (1, 'kamakama', 'kamakama', 'string', '2023-11-14 22:28:51.343000', false, null, null, 'string', '2023-11-14 22:28:51.343000');
INSERT INTO public.kt (id, code, name, created_by, created_date, deleted, deleted_by, deleted_date, last_modified_by, last_modified_date) VALUES (2, 'kamakama', 'kamakama', 'string', '2023-11-14 22:29:11.698000', false, null, null, 'string', '2023-11-14 22:29:11.698000');
INSERT INTO public.kt (id, code, name, created_by, created_date, deleted, deleted_by, deleted_date, last_modified_by, last_modified_date) VALUES (3, 'kamakama', 'kamakama', 'string', '2023-11-14 23:13:41.279000', false, null, null, 'string', '2023-11-14 23:13:41.279000');
