CREATE TABLE obsledovanie
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,

    created_by         VARCHAR(255),
    created_date       TIMESTAMP WITHOUT TIME ZONE,
    deleted            BOOLEAN                                 NOT NULL,
    deleted_by         VARCHAR(255),
    deleted_date       TIMESTAMP WITHOUT TIME ZONE,


    last_modified_by   VARCHAR(255),
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    code               VARCHAR(255),
    name               VARCHAR(255),
    CONSTRAINT pk_obsledovanie PRIMARY KEY (id)
);

INSERT INTO public.obsledovanie (id, created_by, created_date, deleted, deleted_by, deleted_date, last_modified_by, last_modified_date, code, name) VALUES (1, 'string', '2023-11-21 12:51:15.932000', false, null, null, 'string', '2023-11-21 12:51:15.932000', 'string', 'prikol');
INSERT INTO public.obsledovanie (id, created_by, created_date, deleted, deleted_by, deleted_date, last_modified_by, last_modified_date, code, name) VALUES (2, 'string', '2023-11-21 13:07:04.626000', false, null, null, 'string', '2023-11-21 13:07:04.626000', 'string', 'prikol');
